name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
             recipients: |
                  # Users define their subscriptions below
                  help wanted=@YeHu-EM
                  documentation=@YeHu-EM
                  DMC=@YeHu-EM
                  TDC=@YeHu-EM
